service: books

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  hello:
    handler: handler.getBooks
    events:
      - http:
          path: bookstore/books
          method: get
